version = 0.1

[default.deploy.parameters]
stack_name = "mechonway-prod"
resolve_s3 = true
s3_prefix = "mechonway-prod"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" StorageProvider=\"dynamodb\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
